name: Digital Ocean Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Update files
        uses: appleboy/ssh-action@master
        env:
          DEPLOYPATH: "/var/www/davidgarxa.com/public_html/homer"
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          envs: DEPLOYPATH
          script: |
            cd repositories/Homer
            git pull origin
            echo "Update repo"
            echo "$DEPLOYPATH"          
            cp Homer2/index.html $DEPLOYPATH
            cp Homer2/styles.css $DEPLOYPATH
